// Mock data for OTBOOK

export const mockTickets = [
  {
    id: 1,
    number: '#001',
    category: '콘서트',
    title: 'BLACKPINK WORLD TOUR 2023 BORN PINK',
    date: '2023.09.16',
    venue: '고척스카이돔',
    collector: { name: '박민서', avatar: '박', color: '#7b2ff7' },
    likes: 284,
    color: 'purple',
    grade: 'VIP',
  },
  {
    id: 2,
    number: '#023',
    category: '스포츠',
    title: 'KBO 한국시리즈 2023 최종전',
    date: '2023.11.13',
    venue: '잠실야구장',
    collector: { name: '김태양', avatar: '김', color: '#e03a3a' },
    likes: 197,
    color: 'red',
    grade: 'R',
  },
  {
    id: 3,
    number: '#042',
    category: '뮤지컬',
    title: '오페라의 유령 25주년 공연',
    date: '2024.01.20',
    venue: '블루스퀘어',
    collector: { name: '이서연', avatar: '이', color: '#00c8b0' },
    likes: 156,
    color: 'teal',
    grade: 'S',
  },
  {
    id: 4,
    number: '#067',
    category: '콘서트',
    title: 'IU The Golden Hour 서울',
    date: '2025.05.15',
    venue: '올림픽공원',
    collector: { name: '최지우', avatar: '최', color: '#2a4c9f' },
    likes: 421,
    color: 'navy',
    grade: 'VIP',
  },
  {
    id: 5,
    number: '#089',
    category: '전시',
    title: '반 고흐 인사이드 체험전',
    date: '2023.07.28',
    venue: '코엑스',
    collector: { name: '정민호', avatar: '정', color: '#f0a020' },
    likes: 243,
    color: 'amber',
  },
]

export const mockCategories = [
  '전체',
  '콘서트',
  '스포츠',
  '뮤지컬',
  '전시·아트',
  '영화',
  '기타',
]
